# Generated by Django 2.1.12 on 2019-09-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_institution_is_congento_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionalemaildomain',
            old_name='name',
            new_name='domain',
        ),
    ]
