# Generated by Django 2.1.12 on 2019-09-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190923_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='short_name',
            new_name='acronym',
        ),
    ]
