# Generated by Django 2.1.12 on 2019-09-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalemaildomain',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_domains', to='users.Institution'),
        ),
    ]
