# Generated by Django 2.1.12 on 2019-09-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190923_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='affiliation',
            new_name='institution',
        ),
    ]
