# Generated by Django 2.1.12 on 2019-09-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_institution_to_validate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution_to_validate',
            field=models.CharField(blank=True, max_length=120, verbose_name='Institution (needs validation)'),
        ),
    ]
