# Generated by Django 2.2.7 on 2019-11-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191111_1427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutionalemaildomain',
            unique_together=set(),
        ),
    ]
