version: '3'

volumes:
  local_mysql_data: {}
  local_mysql_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: congento_local_django
    depends_on:
      - mysql
      - mailhog
    volumes:
      - .:/app
    env_file:
        - .env
      # - ./.envs/.local/.django
      # - ./.envs/.local/.mysql
    ports:
      - "8000:8000"
    command: /start

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - local_mysql_data:/var/lib/mysql
      - local_mysql_data_backups:/backups
    env_file:
        - .env
    #   - ./.envs/.local/.mysql

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
