version: '3.6'

services:
  django:
    build: .
    restart: on-failure
    image: congento_production_django
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      WAIT_HOSTS: mysql:3306
    env_file:
        - .env
    command: /start
    networks:
      - swp

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./backups:/backups
    env_file:
      - .env
    networks:
      - swp

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  nginx:
    image: nginx
    restart: always
    depends_on:
      - django
    environment:
      - VIRTUAL_HOST=database.congento.org
      - LETSENCRYPT_HOST=database.congento.org
      - LETSENCRYPT_EMAIL=software@research.fchampalimaud.org
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./media:/media
    networks:
      - swp

networks:
  swp:
    name: swp
