#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ "${DEBUG:-False}" = "True" ]
then
    # Install missing dev dependencies
    pipenv install --dev
    echo "Starting DEVELOPMENT server"
    pipenv run python manage.py migrate
    pipenv run python manage.py runserver_plus 0.0.0.0:8000
else
    echo "Starting PRODUCTION server"
    
    chown -R www-data:www-data /app;

    /setup/.venv/bin/pip list 
    /setup/.venv/bin/python manage.py migrate
    /setup/.venv/bin/python manage.py collectstatic --noinput

    a2ensite congento
    a2enmod wsgi
    a2enmod rewrite
    a2enmod ssl

    apachectl -DFOREGROUND
fi


