#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ "${DEBUG:-False}" = "True" ]
then
    pipenv install --dev
    echo "Starting DEVELOPMENT server"
    pipenv run python manage.py migrate
    pipenv run python manage.py runserver 0.0.0.0:8000
else
    pipenv install --deploy --ignore-pipfile
    echo "Starting PRODUCTION server"
    pipenv run python manage.py migrate
    pipenv run python manage.py collectstatic --noinput
    pipenv run gunicorn conf.wsgi --bind 0.0.0.0:5000
fi


