# Generated by Django 2.2.1 on 2019-05-08 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zebrafish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('background', models.CharField(max_length=20)),
                ('genotype', models.CharField(max_length=20)),
                ('phenotype', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=20)),
                ('availability', models.CharField(choices=[('live', 'Live'), ('cryo', 'Cryopreserved'), ('both', 'Live & Cryopreserved'), ('none', 'Unavailable')], max_length=4)),
                ('comments', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('mta', models.BooleanField(default=False, verbose_name='MTA')),
                ('line_name', models.CharField(max_length=20)),
                ('line_number', models.CharField(max_length=20)),
                ('line_type', models.CharField(choices=[('wt', 'WT'), ('tg', 'Tg'), ('mu', 'Mutant'), ('cko', 'CRISPR KO'), ('cki', 'CRISPR KI'), ('other', 'Other')], max_length=5)),
                ('line_type_other', models.CharField(blank=True, max_length=20, verbose_name='')),
                ('remote_id', models.BigIntegerField(verbose_name='Remote id')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congentodb.Institution')),
            ],
            options={
                'verbose_name_plural': 'zebrafish',
            },
        ),
        migrations.CreateModel(
            name='Rodent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('species', models.CharField(choices=[('rat', 'Rat'), ('mouse', 'Mouse')], max_length=5)),
                ('strain_name', models.CharField(max_length=20)),
                ('common_name', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=20)),
                ('availability', models.CharField(choices=[('live', 'Live'), ('cryo', 'Cryopreserved'), ('both', 'Live & Cryopreserved'), ('none', 'Unavailable')], max_length=4)),
                ('comments', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('mta', models.BooleanField(default=False, verbose_name='MTA')),
                ('background', models.CharField(choices=[('c57bl', 'C57BL/6'), ('balb', 'Balb/c'), ('sv', '129sv'), ('fvb', 'FVB'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=5)),
                ('background_other', models.CharField(blank=True, max_length=20, verbose_name='Other')),
                ('genotype', models.CharField(choices=[('wt', 'WT'), ('homo', 'Homo'), ('het', 'Het'), ('hemi', 'Hemi'), ('both', 'Homo/Het'), ('other', 'Other')], max_length=5)),
                ('genotype_other', models.CharField(blank=True, max_length=20, verbose_name='Other')),
                ('model_type', models.CharField(choices=[('wt', 'WT'), ('tg', 'Transgenic'), ('ko', 'KO'), ('cre', 'Cre/flox'), ('other', 'Other')], max_length=5)),
                ('model_type_other', models.CharField(blank=True, max_length=20, verbose_name='Other')),
                ('remote_id', models.BigIntegerField(verbose_name='Remote id')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congentodb.Institution')),
            ],
            options={
                'verbose_name_plural': 'rodent',
            },
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('chrx', models.CharField(blank=True, max_length=60, null=True, verbose_name='chrX')),
                ('chry', models.CharField(blank=True, max_length=60, null=True, verbose_name='chrY')),
                ('bal1', models.CharField(blank=True, max_length=60, null=True, verbose_name='bal1')),
                ('chr2', models.CharField(blank=True, max_length=60, null=True, verbose_name='chr2')),
                ('bal2', models.CharField(blank=True, max_length=60, null=True, verbose_name='bal2')),
                ('chr3', models.CharField(blank=True, max_length=60, null=True, verbose_name='chr3')),
                ('bal3', models.CharField(blank=True, max_length=60, null=True, verbose_name='bal3')),
                ('chr4', models.CharField(blank=True, max_length=60, null=True, verbose_name='chr4')),
                ('chru', models.CharField(blank=True, max_length=60, null=True, verbose_name='chrU')),
                ('legacy1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Legacy ID 1')),
                ('legacy2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Legacy ID 2')),
                ('legacy3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Legacy ID 3')),
                ('flydbid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fly DB ID')),
                ('hospital', models.BooleanField(verbose_name='Hospital')),
                ('died', models.BooleanField(verbose_name='Died')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('specie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specie')),
                ('remote_id', models.BigIntegerField(verbose_name='Remote id')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congentodb.Institution')),
            ],
            options={
                'verbose_name': 'Fly stock',
                'verbose_name_plural': 'Flies stock',
                'ordering': ['-id'],
            },
        ),
    ]
