# Generated by Django 2.2.1 on 2019-09-17 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zebrafish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('background', models.CharField(max_length=20)),
                ('genotype', models.CharField(max_length=20)),
                ('phenotype', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=20)),
                ('availability', models.CharField(choices=[('live', 'Live'), ('cryo', 'Cryopreserved'), ('both', 'Live & Cryopreserved'), ('none', 'Unavailable')], max_length=4)),
                ('comments', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('mta', models.BooleanField(default=False, verbose_name='MTA')),
                ('line_name', models.CharField(max_length=20)),
                ('line_number', models.CharField(max_length=20)),
                ('line_type', models.CharField(choices=[('wt', 'WT'), ('tg', 'Tg'), ('mu', 'Mutant'), ('cko', 'CRISPR KO'), ('cki', 'CRISPR KI'), ('other', 'Other')], max_length=5)),
                ('line_type_other', models.CharField(blank=True, max_length=20, verbose_name='')),
                ('remote_id', models.BigIntegerField(verbose_name='Remote id')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congentodb.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Rodent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('availability', models.CharField(choices=[('live', 'Live'), ('cryo', 'Cryopreserved'), ('both', 'Live & Cryopreserved'), ('none', 'Unavailable')], max_length=4)),
                ('link', models.URLField(blank=True)),
                ('species', models.CharField(max_length=80)),
                ('strain_name', models.CharField(max_length=20)),
                ('common_name', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=40)),
                ('origin_other', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('background', models.CharField(blank=True, max_length=80, null=True)),
                ('zygosity', models.CharField(blank=True, max_length=20)),
                ('line_description', models.TextField(blank=True)),
                ('coat_color', models.CharField(blank=True, max_length=40, null=True)),
                ('reporter_gene', models.CharField(blank=True, max_length=40, null=True)),
                ('inducible_cassette', models.CharField(blank=True, max_length=40, null=True)),
                ('remote_id', models.BigIntegerField(verbose_name='Remote id')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congentodb.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('categories', models.TextField(blank=True, null=True, verbose_name='Category')),
                ('species', models.CharField(max_length=80, verbose_name='Species')),
                ('origin', models.CharField(choices=[('center', 'Stock Center'), ('internal', 'Internal Lab'), ('external', 'External Lab')], default='center', max_length=8)),
                ('origin_center', models.CharField(blank=True, max_length=100, null=True, verbose_name='Species')),
                ('chrx', models.CharField(blank=True, max_length=60, verbose_name='Chromosome X')),
                ('chry', models.CharField(blank=True, max_length=60, verbose_name='Chromosome Y')),
                ('chr2', models.CharField(blank=True, max_length=60, verbose_name='Chromosome 2')),
                ('chr3', models.CharField(blank=True, max_length=60, verbose_name='Chromosome 3')),
                ('chr4', models.CharField(blank=True, max_length=60, verbose_name='Chromosome 4')),
                ('bal1', models.CharField(blank=True, max_length=60, verbose_name='Balancer 1')),
                ('bal2', models.CharField(blank=True, max_length=60, verbose_name='Balancer 2')),
                ('bal3', models.CharField(blank=True, max_length=60, verbose_name='Balancer 3')),
                ('chru', models.CharField(blank=True, max_length=60, verbose_name='Unknown genotype')),
                ('special_husbandry_conditions', models.TextField(blank=True)),
                ('line_description', models.TextField(blank=True)),
                ('remote_id', models.BigIntegerField(verbose_name='Remote id')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congentodb.Institution')),
            ],
            options={
                'verbose_name': 'Fly stock',
                'verbose_name_plural': 'Flies stock',
                'ordering': ['-id'],
            },
        ),
    ]
