# Generated by Django 2.2.1 on 2019-05-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rodent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zebrafish',
            options={},
        ),
        migrations.RemoveField(
            model_name='fly',
            name='died',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='hospital',
        ),
    ]
