# Generated by Django 2.1.8 on 2019-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0002_auto_20190511_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rodent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
