# Generated by Django 2.1.12 on 2019-09-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0002_auto_20190918_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='congentodb.Institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fish',
            name='remote_id',
            field=models.BigIntegerField(verbose_name='Remote ID'),
        ),
    ]
