# Generated by Django 2.1.12 on 2019-09-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0003_auto_20190918_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fish',
            options={'verbose_name': 'fish', 'verbose_name_plural': 'fish'},
        ),
    ]
