# Generated by Django 2.1.12 on 2019-09-20 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0004_auto_20190918_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='congento_institution', to=settings.AUTH_USER_MODEL),
        ),
    ]
