# Generated by Django 2.1.12 on 2019-09-20 14:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('congentodb', '0006_auto_20190920_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institution',
            new_name='CongentoMember',
        ),
        migrations.RenameField(
            model_name='fish',
            old_name='institution',
            new_name='congento_member',
        ),
        migrations.RenameField(
            model_name='fly',
            old_name='institution',
            new_name='congento_member',
        ),
        migrations.RenameField(
            model_name='rodent',
            old_name='institution',
            new_name='congento_member',
        ),
    ]
