# Generated by Django 2.1.12 on 2019-09-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_institution_is_congento_member'),
        ('congentodb', '0007_auto_20190920_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='congentomember',
            name='institution',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='congento_member', to='users.Institution'),
            preserve_default=False,
        ),
    ]
