# Generated by Django 2.1.12 on 2019-09-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0009_remove_congentomember_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congentomember',
            name='institution',
            field=models.OneToOneField(limit_choices_to={'is_congento_member': True}, on_delete=django.db.models.deletion.CASCADE, related_name='congento_member', to='users.Institution'),
        ),
    ]
