# Generated by Django 2.1.12 on 2019-09-20 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0010_auto_20190920_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congentomember',
            name='api_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='congento_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
