# Generated by Django 2.2.5 on 2019-09-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0012_auto_20190920_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='origin_center',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stock center'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='remote_id',
            field=models.BigIntegerField(verbose_name='Remote ID'),
        ),
    ]
