# Generated by Django 2.2.5 on 2019-09-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0013_auto_20190924_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='categories',
            field=models.TextField(blank=True, null=True, verbose_name='Categories'),
        ),
    ]
