# Generated by Django 2.2.5 on 2019-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0015_auto_20190925_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodent',
            name='remote_id',
            field=models.BigIntegerField(verbose_name='Remote ID'),
        ),
    ]
