# Generated by Django 2.2.5 on 2019-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congentodb', '0016_auto_20190925_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='category_name',
            field=models.CharField(max_length=40, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='species_name',
            field=models.CharField(max_length=80, verbose_name='Species'),
        ),
    ]
