# Generated by Django 2.1.8 on 2019-09-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='remote_id',
            field=models.PositiveIntegerField(verbose_name='Remote ID'),
        ),
    ]
