# Generated by Django 2.1.12 on 2019-09-13 13:25

import django.core.management.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('acronym', models.CharField(max_length=20, verbose_name='Acronym')),
                ('key', models.CharField(blank=True, default=django.core.management.utils.get_random_secret_key, max_length=50, verbose_name='Key')),
            ],
        ),
    ]
